"""Add total_capacity column to events table

Revision ID: 2144f6aa9740
Revises: 
Create Date: 2024-06-29 16:01:48.546898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2144f6aa9740'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_capacity', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('gold_price', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('silver_price', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('platinum_price', sa.String(length=100), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('event_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('event_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('platinum_price')
        batch_op.drop_column('silver_price')
        batch_op.drop_column('gold_price')
        batch_op.drop_column('total_capacity')

    # ### end Alembic commands ###
